#!/bin/bash
[[ "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" =~  .*/docker-([a-zA-Z0-9_-]+)/?(.*) ]]

if [ $? ]; then
  [[ "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" =~  .*/([a-zA-Z0-9_-]+)/?(.*) ]]
fi

IMAGE=${BASH_REMATCH[1]}
BRANCH=${BASH_REMATCH[2]}
